name: CI/CD Pipeline

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Teste simples
        run: echo "Build funcionando"

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy simples
        run: echo "Deploy funcionando"
